apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  namespace: {{ include "appsmith.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}