---
- name: deploy cloud init config file
  template: src=templates/cloud-config.cfg dest=/etc/cloud/cloud.cfg.d/defaults.cfg
  become: yes

- name: create group appsmith
  group: name=appsmith state=present
  become: yes

- name: create user appsmith
  user: name=appsmith groups="appsmith"
  become: yes

- name: add sudoers group for user appsmith
  copy:
    content: 'appsmith ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/appsmith
    mode: 0440
    owner: root
    group: root
  become: yes
